# Generated by Django 5.0.2 on 2024-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_join_date_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('contents', models.CharField(max_length=200)),
            ],
        ),
    ]
